services:
  - type: web
    name: video-upload-api
    env: python3
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker py.vid_sender:app